version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../data/processed_data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped