version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/backend

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5500:80"
    depends_on:
      - backend
